#!/bin/bash

DEST_BACKUPS="/mnt/c/Users/Pepita/Documents/backups"
NOTES_WORK_DIR=$HOME/code/notes/work/
BASH_RC_PATH=$HOME/.bashrc
PROFILE_PATH=$HOME/.profile
BASH_ALIASES_PATH=$HOME/.bash_aliases

if [[ -d $NOTES_WORK_DIR ]]; then
    rsync -avz --delete "$NOTES_WORK_DIR" "$DEST_BACKUPS/notes"
fi

if [[ -f $BASH_RC_PATH ]]; then
    rsync -avz --delete $BASH_RC_PATH $DEST_BACKUPS
    rsync -avz --delete $PROFILE_PATH $DEST_BACKUPS
    rsync -avz --delete $BASH_ALIASES_PATH $DEST_BACKUPS
fi
