#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    items=`find ~/code -maxdepth 2 -mindepth 1 -type d`
    items+=`echo -e "\n/tmp"`
    selected=`echo "$items" | fzf`
fi

dirname=`basename $selected | sed 's/\./_/g'`

tmux split-window -v -c "$selected"
